// <auto-generated />
namespace ProgramStudent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Max30addtoName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Max30addtoName));
        
        string IMigrationMetadata.Id
        {
            get { return "201802231451260_Max 30 add to Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
